# Generated by Django 5.1.3 on 2024-11-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
